#!/bin/bash
service_name="company-account-service"
source ./env/bin/activate

start_containers(){
    sudo docker run -it --name ${service_name}-rabbitmq-local -p 5672:5672 -p 15672:15672 -p 1883:1883 -p 15675:15675 -d rabbitmq:3
}

remove_containers(){
    sudo docker stop ${service_name}-rabbitmq-local 2> /dev/null
    sudo docker rm --volumes ${service_name}-rabbitmq-local 2> /dev/null
}


echo "----------------------"
echo "Exporting Variables"
#Application variables 
export JWT_SECRET=secret
#export DATABASE_URL=sqlite:///test.sqlite


echo "----------------------"
echo "Starting Containers"
#Ensure containers aren't running
remove_containers
#Start Containers
start_containers

echo "----------------------"
echo "Starting Service"
uvicorn app.api.main:app --reload --port 8000


echo "----------------------"
echo "Stopping Containers"
remove_containers
#rm test.sqlite 2> /dev/null