#!/bin/bash
export PYTHONPATH=$PYTHONPATH:../
echo $PYTHONPATH
service_name="company-account-service"
source ./env/bin/activate
source ../setenv

echo "----------------------"
echo "Exporting Variables"
#Application variables
export JWT_SECRET=secret
export ENV=DEV
rm env.env 2>/dev/null
echo 'true' > env.env
# export database_url="postgresql+asyncpg://test:test@localhost:5432/test"


echo "----------------------"
echo "Starting Service"
uvicorn app.api.main:app --reload --port 8000

rm env.env 2>/dev/null
