#!/bin/bash
export PYTHONPATH=$PYTHONPATH:../
service_name="company-device-service"
source ./env/bin/activate
source ../setenv


echo "----------------------"
echo "Exporting Variables"
#Application variables
export JWT_SECRET=secret
export ENV=DEV
rm env.env 2>/dev/null
echo 'true' > env.env

echo "----------------------"
echo "Starting Service"
uvicorn app.api.main:app --reload --port 8001

rm env.env 2>/dev/null
