#!/bin/bash
export PYTHONPATH=$PYTHONPATH:../

service_name="deviceservice"
source ./env/bin/activate
source ../setenv

echo "----------------------"
echo "Exporting Variables"
#Application variables
export JWT_SECRET=secret


rm -r ./schemas  2> /dev/null
cp -r ../schemas ./schemas


echo "----------------------"
echo "Starting Service"
#uncomment below if using fast api
uvicorn app.api.main:app --reload --port 8002


rm -r ./schemas 2> /dev/null
