version: "3.9"  # optional since v1.27.0
services:
  company-account-service:
    build :  
      context: ..
      dockerfile: company-account-service/Dockerfile
    ports:
      - "8000:8080"
    environment:
      ENV: DEV
      database_url : sqlite:///test.sqlite